#!/bin/sh

OPT=`getopt -o o -- "$@"`
eval set -- "$OPT"

for i; do
    case $i in
	--) shift; break;;
	-o) OPT_O="true";;
    esac
    shift
done

if test -z "$2"; then
    MAN_SEC=9 # xxx
    MAN_PAGE=$1
else
    MAN_SEC=$1
    MAN_PAGE=$2
fi
MAN_FILE=ja/src/share/man/man$MAN_SEC/$MAN_PAGE.$MAN_SEC
test "$OPT_O" != "true" && MAN_FILE=$MAN_FILE.ja

test -n "$MAN_SEC" || exit 1
test -n "$MAN_PAGE" || exit 2
test -f "$MAN_FILE" || exit 3

groff -K utf8 -mandoc -Tutf8 $MAN_FILE | lv
