#!/bin/sh

DIR_TOOLS=$PWD/tools/
TOPDIR=$PWD
DATE=`LC_ALL=C LANGUAGE=C LANG=C date`

rm -rf $TOPDIR/html/*

cd $TOPDIR/ja/ &&

FILES_MAN=`find src/share/man/man9 -name "*.9"`
FILES_JMAN=`find src/share/man/man9 -name "*.9.ja"`

for i in $FILES_MAN $FILES_JMAN; do
    mkdir -p ../html/`dirname $i`
    $DIR_TOOLS/man_utf8 $i | $DIR_TOOLS/rofftxt2html $i > ../html/$i.html
done

cd $TOPDIR/html/ &&
haml $DIR_TOOLS/output_htmls_files/tree.haml tree.html
haml $DIR_TOOLS/output_htmls_files/index.haml index.html
