#!/usr/bin/env ruby

require 'date'

def usage
  puts "Usage: roffgettext hoge.9 > hoge.9.pot"
  exit 1
end

class UngetsFile < File
  def ungets(s)
    @ungetsed = [] unless @ungetsed
    @ungetsed.push s
  end
  def gets
    if @ungetsed && @ungetsed.size > 0
      @ungetsed.shift
    else
      super
    end
  end
end

class GettextMsgids
  def initialize
    @msgids = []
  end
  def push_oneline(f, t)
    l = [f.lineno.to_s]
    m = 'msgid "' + t.gsub('"','\"') + '"' + "\n"
    m += 'msgstr ""' + "\n\n"
    @msgids.push({:linenos => l, :msgidstr => m})
  end
  def push_morelines(f)
    l = [(1 + f.lineno).to_s]
    m = 'msgid ""' + "\n"

    f.each{|a|
      if a =~ /^\.Sh/ || a =~ /^\.Pp/
        f.ungets a
        break
      end
      m += '"' + a.gsub("\n",'\n').gsub('"','\"') + '"' + "\n"
    }

    m += 'msgstr ""' + "\n\n"
    @msgids.push({:linenos => l, :msgidstr => m})
  end
  def printout
    @msgids.each_index{|i|
      a = @msgids[i]
      puts("#: #{Filename}:" + a[:linenos].join(" #{Filename}:"))
      puts "#, c-format"
      puts a[:msgidstr]
    }
  end
end

usage if ARGV.size != 1
Filename = ARGV[0]

# header
f = UngetsFile.open(Filename)
Version = f.gets.scan(/\$.+\$/).first.gsub("$","")
NowDate = DateTime.now
NowDateStr = sprintf("%04d-%02d-%02d %02d:%02d%s",
                     NowDate.year, NowDate.month, NowDate.day,
                     NowDate.hour, NowDate.min, NowDate.zone.gsub(":",""))

puts <<EOF
# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: #{Version}\\n"
"Report-Msgid-Bugs-To: kiwamu@debian.or.jp\\n"
"POT-Creation-Date: #{NowDateStr}\\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\\n"
"Language-Team: LANGUAGE <LL@li.org>\\n"
"MIME-Version: 1.0\\n"
"Content-Type: text/plain; charset=CHARSET\\n"
"Content-Transfer-Encoding: 8bit\\n"

EOF

gmsgids = GettextMsgids.new

while s = f.gets
  if s =~ /^\.Nd (.*)/
    gmsgids.push_oneline(f, $1)
  elsif s =~ /^\.Sh NAME/ || s =~ /^\.Sh SYNOPSIS/ || s =~ /^\.Sh SEE ALSO/
    next
  elsif s =~ /^\.Sh/ || s =~ /^\.Pp/
    gmsgids.push_morelines(f)
  end
end

gmsgids.printout
