#!/usr/bin/env ruby

=begin
def usage
  puts "Usage: cat `find share/man -name \"*.?\"` | roffchecktag TAGLISTFILE"
  exit 1
end

usage if ARGV.size != 1
Taglistfile = ARGV.first
=end

$stdin.each{|a|
  if a =~ /^\.(\w+)\s/
    puts $1
  end
}
