#!/bin/sh

TX_PROJECT="test-masterq" # xxx 4test

DIR_TOOLS=$PWD/tools/
TOPDIR=$PWD

FILES_ORIG=`find ja -name "*.9"`

txset() {
    filename=$1

    # example ".../man/man9/man9.i386/splraise.9"
    txpath=`echo $filename | sed -e "s/^.*\/man\/man[^\/]\/man[^\/]\.\([^\/]*\)\/\([^\/]*\)\.\([^\/]\)$/\3-\2-\1/"`
    if [ $filename = $txpath ]; then
        # example ".../man/man9/uvm.9"
	txpath=`echo $i | sed -e "s/^.*\/man\/man[^\/]\/\([^\/]*\)\.\([^\/]\)$/\2-\1/"`
    fi

    mkdir -p $i.po
    $DIR_TOOLS/roffxgettext $i > $i.po/$txpath.pot
    tx set --execute --auto-local -r $TX_PROJECT.$txpath "$filename.po/<lang>.po" --source-lang en --source-file $filename.po/$txpath.pot
}

for i in $FILES_ORIG; do
    txset $i
done
